### PR TITLE
add thor wikfeldt

### PR DESCRIPTION
**Pull request by wikfeldt**
added myself to people.yml and added picture to media folder

### CODE REVIEW

**Comment by bast** [comment]
Thank you!

**Comment by bast** [comment]
Something is strange: when I click your name on https://neic.nordforsk.org/about/team/coderefinery/, I land "nowhere". Something else seems to be missing. I need to document better how to add people.

**Comment by wikfeldt** [comment]
hmm, that's very strange. I'll look into it

**Comment by wikfeldt** [comment]
maybe the image is too large. I'll try with a smaller one, but right now i have to hurry to pick up my daughter. will upload smaller image in ~2 hours

**Comment by bast** [comment]
Don't think the problem is image size. There is something in the Jekyll setup that I don't know. I will find some doc from Slack on this.

**Pull request merged**
